//! Colour swatches for the two built-in presets.
//!
//! GENERATED by `tools/build_palettes.py` from `assets/ayu-graphite-base.toml`.
//! Edit the base palette and rerun the generator; edits here are overwritten.
//!
//! The two mods line up 1:1 — every name in [`dark`] has a [`light`] peer with
//! the matching role — which is what lets `palette_struct!` fill both presets
//! from one `field => CONST` list.

/// The built-in dark preset.
pub(crate) mod dark {
    use palantir::Color;

    use crate::gui::theme::hover_color::HoverColor;
    use crate::gui::theme::type_colors::TypeColors;

    /// Ground fill behind the whole graph.
    pub(crate) const CANVAS_BG: Color = Color::hex(0x161514);

    /// Backdrop grid dot colour.
    pub(crate) const CANVAS_DOT: Color = Color::hex(0x3d3c3b);

    /// Rubber-band sweep and committed selection halo — one swatch so
    /// "in the selection" reads the same from drag to commit.
    pub(crate) const SELECTION_RECT: Color = Color::hex(0x59d4ff);

    /// A wire whose endpoint no longer resolves.
    pub(crate) const CONNECTION_BROKEN: Color = Color::hex(0xff6b52);

    /// The scribble that cuts wires.
    pub(crate) const BREAKER_STROKE: Color = Color::hex(0xff6b52);

    /// Node body fill. The same swatch palantir gives its own surfaces:
    /// nodes and popups sit on one surface tier by design.
    pub(crate) const NODE_FILL: Color = Color::hex(0x323130);

    /// Resting outline. Transparent on the dark ground, where the ambient
    /// shadow carries the edge and the stroke slot is reserved for the
    /// selection / breaker / missing colours; a light surface needs the
    /// hairline, because a shadow alone reads mushy on near-white.
    pub(crate) const NODE_BORDER: Color = Color::TRANSPARENT;

    /// Header band, a step off the body so the band reads against it.
    pub(crate) const HEADER_FILL: Color = Color::hex(0x484745);

    /// De-emphasized chrome ink.
    pub(crate) const TEXT_MUTED: Color = Color::hex(0xaaaaa8);

    /// Port + event label ink. Muted on the dark ground; full-strength on
    /// the light one, where the muted grey drops under 3:1 on the card fill.
    pub(crate) const PORT_LABEL: Color = Color::hex(0xaaaaa8);

    /// Ambient elevation shadow. A near-black canvas needs a lot of alpha
    /// before a shadow registers at all; a light surface needs far less.
    pub(crate) const NODE_AMBIENT_SHADOW: Color = Color::hexa(0x00000080);

    /// Top-chrome fill behind the menu bar + tab strip — the surround the
    /// graph and its nodes sit inside.
    pub(crate) const CHROME_FILL: Color = Color::hex(0x1f1e1d);

    /// Inactive tab chip: the rung between `CHROME_FILL` and the card
    /// surface, so an unselected tab reads as a chip and not a bare label.
    pub(crate) const TAB_INACTIVE: Color = Color::hex(0x282726);

    /// Inspect chip and pinned-inspector outline.
    pub(crate) const BADGE_GRAPH: Color = Color::hex(0x59d4ff);

    /// Sink chip.
    pub(crate) const BADGE_SINK: Color = Color::hex(0xff6b52);

    /// Persist-to-disk cache chip.
    pub(crate) const BADGE_CACHE: Color = Color::hex(0xffd44a);

    /// Impure marker — the node recomputes every run and is never cached.
    /// Shares the violet with `TypeColors::image`: the base carries no
    /// second pink, and the two never meet (a header glyph vs. a wire).
    pub(crate) const BADGE_IMPURE: Color = Color::hex(0xd897ff);

    /// It worked / it ran.
    pub(crate) const STATUS_SUCCESS: Color = Color::hex(0xdaff58);

    /// It was reused from cache.
    pub(crate) const STATUS_INFO: Color = Color::hex(0x59d4ff);

    /// It is happening right now. Shares the lilac with
    /// `TypeColors::path`, as it always has.
    pub(crate) const STATUS_BUSY: Color = Color::hex(0xe8c2ff);

    /// It is incomplete but not broken.
    pub(crate) const STATUS_WARNING: Color = Color::hex(0xffa63d);

    /// It failed.
    pub(crate) const STATUS_ERROR: Color = Color::hex(0xff6b52);

    /// Palantir's primary ink.
    pub(crate) const PAL_TEXT: Color = Color::hex(0xe2dfd3);

    /// Palantir's disabled ink.
    pub(crate) const PAL_TEXT_DISABLED: Color = Color::hex(0x878a8d);

    /// Palantir's hovered control fill.
    pub(crate) const PAL_ELEM_HOVER: Color = Color::hex(0x3d3c3b);

    /// Palantir's pressed control fill.
    pub(crate) const PAL_ELEM_ACTIVE: Color = Color::hex(0x484745);

    /// Palantir's focus ring.
    pub(crate) const PAL_BORDER_FOCUSED: Color = Color::hex(0x105577);

    /// Positional swatch for untyped input ports.
    pub(crate) const INPUT_PORT: HoverColor = HoverColor {
        rest: Color::hex(0xdaff58),
        hover: Color::hex(0xeaff9a),
    };

    /// Positional swatch for untyped output ports.
    pub(crate) const OUTPUT_PORT: HoverColor = HoverColor {
        rest: Color::hex(0xffa63d),
        hover: Color::hex(0xffd44a),
    };

    /// Event emitters, subscription pins and event wires — the same red as
    /// the sink marker the pin sits beside, so the trigger machinery reads
    /// as one family. Shape keeps events apart from data ports.
    pub(crate) const EVENT_PORT: HoverColor = HoverColor {
        rest: Color::hex(0xff6b52),
        hover: Color::hex(0xff8f7a),
    };

    /// Data-type hues for wires and typed port circles.
    pub(crate) const TYPE_COLORS: TypeColors = TypeColors {
        boolean: Color::hex(0xff8f7a),
        int: Color::hex(0x69ffd1),
        float: Color::hex(0x7adcf3),
        string: Color::hex(0xffdd8c),
        path: Color::hex(0xe8c2ff),
        image: Color::hex(0xd897ff),
        ramp: [
            Color::hex(0xffa63d),
            Color::hex(0xdaff58),
            Color::hex(0x77adbc),
            Color::hex(0xc7c6bf),
        ],
    };
}

/// The built-in light preset.
pub(crate) mod light {
    use palantir::Color;

    use crate::gui::theme::hover_color::HoverColor;
    use crate::gui::theme::type_colors::TypeColors;

    /// Ground fill behind the whole graph.
    pub(crate) const CANVAS_BG: Color = Color::hex(0xfdfbfa);

    /// Backdrop grid dot colour.
    pub(crate) const CANVAS_DOT: Color = Color::hex(0xcac9c7);

    /// Rubber-band sweep and committed selection halo — one swatch so
    /// "in the selection" reads the same from drag to commit.
    pub(crate) const SELECTION_RECT: Color = Color::hex(0x42b0d5);

    /// A wire whose endpoint no longer resolves.
    pub(crate) const CONNECTION_BROKEN: Color = Color::hex(0xe6634d);

    /// The scribble that cuts wires.
    pub(crate) const BREAKER_STROKE: Color = Color::hex(0xe6634d);

    /// Node body fill. The same swatch palantir gives its own surfaces:
    /// nodes and popups sit on one surface tier by design.
    pub(crate) const NODE_FILL: Color = Color::hex(0xe5e3e2);

    /// Resting outline. Transparent on the dark ground, where the ambient
    /// shadow carries the edge and the stroke slot is reserved for the
    /// selection / breaker / missing colours; a light surface needs the
    /// hairline, because a shadow alone reads mushy on near-white.
    pub(crate) const NODE_BORDER: Color = Color::hex(0xcac9c7);

    /// Header band, a step off the body so the band reads against it.
    pub(crate) const HEADER_FILL: Color = Color::hex(0xd4d2d0);

    /// De-emphasized chrome ink.
    pub(crate) const TEXT_MUTED: Color = Color::hex(0x898987);

    /// Port + event label ink. Muted on the dark ground; full-strength on
    /// the light one, where the muted grey drops under 3:1 on the card fill.
    pub(crate) const PORT_LABEL: Color = Color::hex(0x68665e);

    /// Ambient elevation shadow. A near-black canvas needs a lot of alpha
    /// before a shadow registers at all; a light surface needs far less.
    pub(crate) const NODE_AMBIENT_SHADOW: Color = Color::hexa(0x00000033);

    /// Top-chrome fill behind the menu bar + tab strip — the surround the
    /// graph and its nodes sit inside.
    pub(crate) const CHROME_FILL: Color = Color::hex(0xf5f3f2);

    /// Inactive tab chip: the rung between `CHROME_FILL` and the card
    /// surface, so an unselected tab reads as a chip and not a bare label.
    pub(crate) const TAB_INACTIVE: Color = Color::hex(0xedecea);

    /// Inspect chip and pinned-inspector outline.
    pub(crate) const BADGE_GRAPH: Color = Color::hex(0x42b0d5);

    /// Sink chip.
    pub(crate) const BADGE_SINK: Color = Color::hex(0xe6634d);

    /// Persist-to-disk cache chip.
    pub(crate) const BADGE_CACHE: Color = Color::hex(0xcba626);

    /// Impure marker — the node recomputes every run and is never cached.
    /// Shares the violet with `TypeColors::image`: the base carries no
    /// second pink, and the two never meet (a header glyph vs. a wire).
    pub(crate) const BADGE_IMPURE: Color = Color::hex(0xb980db);

    /// It worked / it ran.
    pub(crate) const STATUS_SUCCESS: Color = Color::hex(0xa3c226);

    /// It was reused from cache.
    pub(crate) const STATUS_INFO: Color = Color::hex(0x42b0d5);

    /// It is happening right now. Shares the lilac with
    /// `TypeColors::path`, as it always has.
    pub(crate) const STATUS_BUSY: Color = Color::hex(0xba99ce);

    /// It is incomplete but not broken.
    pub(crate) const STATUS_WARNING: Color = Color::hex(0xd88a2d);

    /// It failed.
    pub(crate) const STATUS_ERROR: Color = Color::hex(0xe6634d);

    /// Palantir's primary ink.
    pub(crate) const PAL_TEXT: Color = Color::hex(0x68665e);

    /// Palantir's disabled ink.
    pub(crate) const PAL_TEXT_DISABLED: Color = Color::hex(0x9ea0a3);

    /// Palantir's hovered control fill.
    pub(crate) const PAL_ELEM_HOVER: Color = Color::hex(0xdcdbd9);

    /// Palantir's pressed control fill.
    pub(crate) const PAL_ELEM_ACTIVE: Color = Color::hex(0xd4d2d0);

    /// Palantir's focus ring.
    pub(crate) const PAL_BORDER_FOCUSED: Color = Color::hex(0xbae1fa);

    /// Positional swatch for untyped input ports.
    pub(crate) const INPUT_PORT: HoverColor = HoverColor {
        rest: Color::hex(0xa3c226),
        hover: Color::hex(0xaec068),
    };

    /// Positional swatch for untyped output ports.
    pub(crate) const OUTPUT_PORT: HoverColor = HoverColor {
        rest: Color::hex(0xd88a2d),
        hover: Color::hex(0xcba626),
    };

    /// Event emitters, subscription pins and event wires — the same red as
    /// the sink marker the pin sits beside, so the trigger machinery reads
    /// as one family. Shape keeps events apart from data ports.
    pub(crate) const EVENT_PORT: HoverColor = HoverColor {
        rest: Color::hex(0xe6634d),
        hover: Color::hex(0xdd7a68),
    };

    /// Data-type hues for wires and typed port circles.
    pub(crate) const TYPE_COLORS: TypeColors = TypeColors {
        boolean: Color::hex(0xdd7a68),
        int: Color::hex(0x40c8a1),
        float: Color::hex(0x5db3c7),
        string: Color::hex(0xc8aa64),
        path: Color::hex(0xba99ce),
        image: Color::hex(0xb980db),
        ramp: [
            Color::hex(0xd88a2d),
            Color::hex(0xa3c226),
            Color::hex(0x6c95a1),
            Color::hex(0x777671),
        ],
    };
}
