use super::*;

use static_assertions::assert_not_impl_any;

assert_not_impl_any!(Theme: Copy);
assert_not_impl_any!(ChromeColors: Copy);
assert_not_impl_any!(CanvasTheme: Copy);
assert_not_impl_any!(CardTheme: Copy);
assert_not_impl_any!(PortTheme: Copy);
assert_not_impl_any!(StatusColors: Copy);
assert_not_impl_any!(TypeColors: Copy);
assert_not_impl_any!(ConstValueEditorTheme: Copy);
assert_not_impl_any!(InlineRenameTheme: Copy);

/// Pin which palette role reaches which field, plus the non-trivial
/// palantir tweak, so a regression in `Theme::build`'s wiring, in
/// `palantir_for`, or in `menu_button_for` fails loudly. Against
/// the loaded palette rather than hex literals: the values are the
/// palette's to choose, but landing `header_fill` in `canvas.bg` is
/// still a bug.
#[test]
fn default_wiring_and_menu_tweak() {
    let p = Palette::load();
    let theme = Theme::default();
    assert_eq!(theme.canvas.bg, p.canvas_bg);
    assert_eq!(theme.card.header_fill, p.header_fill);
    assert_eq!(theme.ports.input, p.input_port);
    assert_eq!(theme.ports.output, p.output_port);
    assert_eq!(theme.colors.badge_cache, p.badge_cache);
    assert_eq!(theme.colors.badge_impure, p.badge_impure);
    assert_eq!(theme.status.busy, p.status_busy);
    // Each of those is a distinct role, so a palette that collapsed them
    // onto one colour would pass every assertion above.
    assert_ne!(theme.canvas.bg, theme.card.header_fill);
    assert_ne!(theme.ports.input, theme.ports.output);
    // The palantir half is the same palette, not palantir's own default.
    assert_eq!(theme.palantir.window_clear, p.canvas_bg);
    assert!(theme.palantir.tooltip.max_size.h.is_infinite());
    // The menu-bar font was shrunk from palantir's default to ours.
    let menu_text = theme
        .menu_button
        .looks
        .normal
        .text
        .expect("menu button carries an explicit text style");
    assert_eq!(menu_text.font_size_px, theme.text.body);
}

/// Every badge is legible against every other, because a node's head
/// can carry several at once.
///
/// A badge sharing a hue with a wire type or a status is fine and
/// common — the palette resolves both against one upstream semantic
/// layer, and the two never share a surface. Two badges do, so this is
/// the pair the roster cannot be allowed to collapse. Like
/// [`chrome_surfaces_stack_darkest_first`], it is a rule a table of
/// colours cannot state about itself.
#[test]
fn badges_are_told_apart_from_each_other() {
    let c = Theme::default().colors;
    let badges = [
        ("badge_graph", c.badge_graph),
        ("badge_sink", c.badge_sink),
        ("badge_cache", c.badge_cache),
        ("badge_impure", c.badge_impure),
    ];
    for (i, (name, color)) in badges.iter().enumerate() {
        for (other_name, other) in &badges[i + 1..] {
            assert_ne!(
                color, other,
                "{name} and {other_name} share a hue, and a head can show both",
            );
        }
    }
}

/// The six chrome surfaces stack in one view — a graph, the bar around
/// it, an inactive tab, a node, a hovered control, a pressed one — so
/// each must be lighter than the one under it. The palette's generator
/// checks this before it writes the file; this is the half that would
/// catch a hand-edited asset, and it is the one rule a table of colours
/// cannot state about itself.
#[test]
fn chrome_surfaces_stack_darkest_first() {
    let p = Palette::load();
    let ladder = [
        ("canvas_bg", p.canvas_bg),
        ("chrome_fill", p.chrome_fill),
        ("tab_inactive", p.tab_inactive),
        ("node_fill", p.node_fill),
        ("elem_mid", p.elem_mid),
        ("header_fill", p.header_fill),
    ];
    for pair in ladder.windows(2) {
        let [(under, lower), (over, upper)] = pair else {
            unreachable!("windows(2) yields pairs")
        };
        assert!(
            luminance(*lower) < luminance(*upper),
            "{under} is not darker than {over} — a surface on it disappears",
        );
    }
}

/// Relative luminance, the WCAG definition. Local to the test: nothing
/// darkroom draws needs it, and the palette it checks is generated by a
/// tool that computes the same number.
fn luminance(c: RgbaF32) -> f32 {
    let channel = |v: f32| {
        if v <= 0.04045 {
            v / 12.92
        } else {
            ((v + 0.055) / 1.055).powf(2.4)
        }
    };
    let srgb = c.to_srgba_u8();
    0.2126 * channel(f32::from(srgb.r) / 255.0)
        + 0.7152 * channel(f32::from(srgb.g) / 255.0)
        + 0.0722 * channel(f32::from(srgb.b) / 255.0)
}
